/* Automatically generated by Amaranth 0.5.9. Do not edit. */
/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post128, git sha1 b5170e139) */

module blinky(clk27_0__io);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire [23:0] \$2 ;
  wire \$3 ;
  wire [6:0] \$4 ;
  reg \$5 ;
  reg [22:0] \$6 ;
  reg [5:0] \$7 ;
  wire clk;
  (* keep = "true" *)
  input clk27_0__io;
  wire clk27_0__io;
  reg do_shift = 1'h0;
  wire [5:0] leds;
  wire rst;
  reg [5:0] runner = 6'h01;
  reg [22:0] timer = 23'h66ff2f;
  assign \$3  = runner == 6'h20;
  assign leds = ~ runner;
  always @(posedge clk)
    do_shift <= \$5 ;
  always @(posedge clk)
    timer <= \$6 ;
  always @(posedge clk)
    runner <= \$7 ;
  assign \$1  = | timer;
  assign \$2  = timer - 1'h1;
  \blinky.cd_sync  cd_sync (
    .clk(clk),
    .clk27_0__io(clk27_0__io),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$5  = 1'h0;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      \$5  = 1'h1;
    end
    if (rst) begin
      \$5  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$6  = \$2 [22:0];
    end else begin
      \$6  = 23'h66ff2f;
    end
    if (rst) begin
      \$6  = 23'h66ff2f;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$7  = runner;
    if (do_shift) begin
      (* full_case = 32'd1 *)
      if (\$3 ) begin
        \$7  = 6'h01;
      end else begin
        \$7  = \$4 [5:0];
      end
    end
    if (rst) begin
      \$7  = 6'h01;
    end
  end
  assign \$4  = { runner, 1'h0 };
endmodule

module \blinky.cd_sync (rst, clk27_0__io, clk);
  output clk;
  wire clk;
  input clk27_0__io;
  wire clk27_0__io;
  wire i;
  output rst;
  wire rst;
  \blinky.cd_sync.clk_buf  clk_buf (
    .clk27_0__io(clk27_0__io),
    .i(clk)
  );
  \blinky.cd_sync.reset_sync  reset_sync (
    .async_ff_clk(clk),
    .stage1(rst)
  );
  assign i = clk;
endmodule

module \blinky.cd_sync.clk_buf (clk27_0__io, i);
  input clk27_0__io;
  wire clk27_0__io;
  output i;
  wire i;
  wire \i$1 ;
  \blinky.cd_sync.clk_buf.buf  \buf  (
    .clk27_0__io(clk27_0__io),
    .i(\i$1 )
  );
  assign i = \i$1 ;
endmodule

module \blinky.cd_sync.clk_buf.buf (clk27_0__io, i);
  input clk27_0__io;
  wire clk27_0__io;
  output i;
  wire i;
  IBUF buf0 (
    .I(clk27_0__io),
    .O(i)
  );
endmodule

module \blinky.cd_sync.reset_sync (stage1, async_ff_clk);
  input async_ff_clk;
  wire async_ff_clk;
  wire async_ff_rst;
  wire clk;
  (* init = 1'h1 *)
  wire rst;
  reg stage0 = 1'h1;
  output stage1;
  reg stage1 = 1'h1;
  always @(posedge async_ff_clk)
    stage0 <= 1'h0;
  always @(posedge async_ff_clk)
    stage1 <= stage0;
  assign async_ff_rst = 1'h0;
  assign clk = async_ff_clk;
  assign rst = stage1;
endmodule
